name: setup node
description: setup node
inputs:
  version:
    description: node version
    required: false

    # SRC: https://nodejs.org/en/about/previous-releases
    # NOTE: As of 2024-12-26:
    # - LTS = 20x
    # - Active = 20x
    # - Current = 20x
    default: LTS

outputs:
  version:
    description: "Random number"
    value: ${{ steps.node-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: setup node @ ${{ inputs.version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.version }}

    - name: node version
      id: node-version
      shell: bash
      run: |
        node --version
        echo "version=$(echo node --version)" >> $GITHUB_OUTPUT
