on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows

# TODO? or only on triggered worfklow?
# permissions:
#   contents: read

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/commons/.github/shared/actions/checkout@main

      - name: dependency-review
        uses: actions/dependency-review-action@v2
