name: Verify
on:
  push:

jobs:
  npm_lint:
    uses: percebus/commons/.github/shared/workflows/npm_run_lint.yml@main

  npm_audit:
    uses: percebus/commons/.github/shared/workflows/npm_audit.yml@main
