name: Verify
on:
  push:

jobs:
  npm_test:
    runs-on: ubuntu-latest
    name: npm test
    steps:
      - uses: ./.github/actions/checkout
      - uses: ./.github/actions/node_setup
      - uses: ./.github/actions/npm_install
      - name: npm test
        run: npm test
