name: Verify
on:
  push:

env:
  # TODO move to template
  NODE_VERSION: 22

jobs:
  npm_test:
    runs-on: ubuntu-latest
    name: npm test
    steps:
      - uses: ../actions/checkout
      - uses: ../actions/node_setup
      - uses: ../actions/npm_install
      - name: npm test
        run: npm test
