name: "[C]ontinuos [I]ntegration"

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  lint:
    uses: percebus/github-actions-npm/.github/workflows/run_script.yml@main
    with:
      script: lint
