name: Verify
on:
  push:

jobs:
  npm_test:
    runs-on: ubuntu-latest
    name: npm test
    steps:
      - uses: percebus/commons/checkout@main
      - uses: percebus/commons/node_setup@main
      - uses: percebus/commons/npm_install@main
      - name: npm test
        run: npm test
