on:
  push:
  workflow_call: # Indicates that this is a reusable workflow
    # inputs:

jobs:
  npm_audit:
    runs-on: ubuntu-latest
    name: npm audit
    steps:
      # FIXME use relative local path
      - uses: percebus/commons/.github/shared/actions/checkout@main
      - uses: percebus/commons/.github/shared/actions/node_setup@main
      - uses: percebus/commons/.github/shared/actions/npm_install@main

      - name: npm audit
        run: npm audit
        continue-on-error: true
