name: Pull Request

# "This run was triggered by the "push" event, which is unsupported.
#  Please ensure you are using the "pull_request" event for this workflow."
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  audit:
    uses: percebus/github-actions-npm/.github/workflows/dependency-review.yml@main
