name: Test actions/checkout
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  default:
    runs-on: ubuntu-latest
    name: "default"
    steps:
      - uses: ./.github/actions/checkout

      - name: ls repositories
        run: ls ./repositories

  ls_options__matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        ls_options:
          - "-la"
          - "-l"
          - "-a"
        OS:
          - ubuntu-latest
          - macos-latest
        include:
          - OS: windows-latest
            ls_options: ""

    runs-on: ${{ matrix.OS }}
    name: "ls ${{ matrix.ls_options }} @ ${{ matrix.OS }}"
    steps:
      - uses: ./.github/actions/checkout
        with:
          ls_options: ${{ matrix.ls_options }}

  fetch-depth__matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        fetch-depth:
          - 0
          - 1
          - 2

        OS:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.OS }}
    name: "git fetch-depth:${{ matrix.fetch-depth }} @ ${{ matrix.OS }}"
    steps:
      - uses: ./.github/actions/checkout
        with:
          fetch-depth: ${{ matrix.fetch-depth }}
